# Generated by Django 5.2.8 on 2026-02-13 13:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
